version: "3"

vars:
  APP_NAME: tse-analytics
  SOURCE_DIR: tse_analytics

  # Workaround
  SHELL: '{{if eq .OS "Windows_NT"}}powershell{{end}}'

tasks:
  build-resources:
    cmds:
      - pyside6-rcc resources/resources.qrc -o tse_analytics/resources_rc.py

  build-ui:
    cmds:
      - pyside6-uic tse_analytics/views/main_window.ui -o tse_analytics/views/main_window_ui.py
      - pyside6-uic tse_analytics/views/import_csv_dialog.ui -o tse_analytics/views/import_csv_dialog_ui.py
      - pyside6-uic tse_analytics/views/import_tse_dialog.ui -o tse_analytics/views/import_tse_dialog_ui.py
      - pyside6-uic tse_analytics/views/selection/factors/factors_dialog.ui -o tse_analytics/views/selection/factors/factors_dialog_ui.py
      - pyside6-uic tse_analytics/views/selection/variables/add_variable_dialog.ui -o tse_analytics/views/selection/variables/add_variable_dialog_ui.py
      - pyside6-uic tse_analytics/views/datasets/datasets_merge_dialog.ui -o tse_analytics/views/datasets/datasets_merge_dialog_ui.py
      - pyside6-uic tse_analytics/views/datasets/adjust_dataset_dialog.ui -o tse_analytics/views/datasets/adjust_dataset_dialog_ui.py
      - pyside6-uic tse_analytics/views/settings/time_intervals_settings_widget.ui -o tse_analytics/views/settings/time_intervals_settings_widget_ui.py
      - pyside6-uic tse_analytics/views/settings/time_cycles_settings_widget.ui -o tse_analytics/views/settings/time_cycles_settings_widget_ui.py
      - pyside6-uic tse_analytics/views/settings/time_phases_settings_widget.ui -o tse_analytics/views/settings/time_phases_settings_widget_ui.py
      - pyside6-uic tse_analytics/views/settings/binning_settings_widget.ui -o tse_analytics/views/settings/binning_settings_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/n_way_anova/n_way_anova_settings_widget.ui -o tse_analytics/views/analysis/n_way_anova/n_way_anova_settings_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/rm_anova/rm_anova_settings_widget.ui -o tse_analytics/views/analysis/rm_anova/rm_anova_settings_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/mixed_anova/mixed_anova_settings_widget.ui -o tse_analytics/views/analysis/mixed_anova/mixed_anova_settings_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/ancova/ancova_settings_widget.ui -o tse_analytics/views/analysis/ancova/ancova_settings_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/timeseries_decomposition/timeseries_decomposition_settings_widget.ui -o tse_analytics/views/analysis/timeseries_decomposition/timeseries_decomposition_settings_widget_ui.py
      - pyside6-uic tse_analytics/views/about_dialog.ui -o tse_analytics/views/about_dialog_ui.py
      - pyside6-uic tse_analytics/views/reports/reports_widget.ui -o tse_analytics/views/reports/reports_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/drinkfeed/views/drinkfeed_dialog.ui -o tse_analytics/modules/phenomaster/submodules/drinkfeed/views/drinkfeed_dialog_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/drinkfeed/views/drinkfeed_plot_widget.ui -o tse_analytics/modules/phenomaster/submodules/drinkfeed/views/drinkfeed_plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/drinkfeed/views/drinkfeed_settings_widget.ui -o tse_analytics/modules/phenomaster/submodules/drinkfeed/views/drinkfeed_settings_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/drinkfeed/views/drinkfeed_episodes_plot_widget.ui -o tse_analytics/modules/phenomaster/submodules/drinkfeed/views/drinkfeed_episodes_plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/calo/views/calo_dialog.ui -o tse_analytics/modules/phenomaster/submodules/calo/views/calo_dialog_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/calo/views/calo_plot_widget.ui -o tse_analytics/modules/phenomaster/submodules/calo/views/calo_plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/calo/views/calo_settings_widget.ui -o tse_analytics/modules/phenomaster/submodules/calo/views/calo_settings_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/calo/views/calo_gas_settings_widget.ui -o tse_analytics/modules/phenomaster/submodules/calo/views/calo_gas_settings_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/calo/views/calo_test_fit_widget.ui -o tse_analytics/modules/phenomaster/submodules/calo/views/calo_test_fit_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/calo/views/calo_rer_widget.ui -o tse_analytics/modules/phenomaster/submodules/calo/views/calo_rer_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_dialog.ui -o tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_dialog_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_plot_widget.ui -o tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_settings_widget.ui -o tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_settings_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_stream_plot_widget.ui -o tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_stream_plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_heatmap_plot_widget.ui -o tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_heatmap_plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_trajectory_plot_widget.ui -o tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_trajectory_plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_frames_widget.ui -o tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_frames_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/trafficage/views/trafficage_dialog.ui -o tse_analytics/modules/phenomaster/submodules/trafficage/views/trafficage_dialog_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/trafficage/views/trafficage_raw_data_widget.ui -o tse_analytics/modules/phenomaster/submodules/trafficage/views/trafficage_raw_data_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/trafficage/views/trafficage_preprocessed_data_widget.ui -o tse_analytics/modules/phenomaster/submodules/trafficage/views/trafficage_preprocessed_data_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/trafficage/views/trafficage_heatmap_widget.ui -o tse_analytics/modules/phenomaster/submodules/trafficage/views/trafficage_heatmap_widget_ui.py
      - pyside6-uic tse_analytics/modules/intellimaze/submodules/animal_gate/views/animal_gate_dialog.ui -o tse_analytics/modules/intellimaze/submodules/animal_gate/views/animal_gate_dialog_ui.py
      - pyside6-uic tse_analytics/modules/intellimaze/submodules/running_wheel/views/running_wheel_dialog.ui -o tse_analytics/modules/intellimaze/submodules/running_wheel/views/running_wheel_dialog_ui.py
      - pyside6-uic tse_analytics/modules/intellimaze/submodules/consumption_scale/views/consumption_scale_dialog.ui -o tse_analytics/modules/intellimaze/submodules/consumption_scale/views/consumption_scale_dialog_ui.py
      - pyside6-uic tse_analytics/modules/intellicage/views/intellicage_data_widget.ui -o tse_analytics/modules/intellicage/views/intellicage_data_widget_ui.py

  clean:
    desc: remove all build, test, coverage and Python artifacts
    cmds:
      - '{{.SHELL}} rm -r -fo __pycache__/'
      - '{{.SHELL}} rm -r -fo build/'
      - '{{.SHELL}} rm -r -fo dist/'
      - '{{.SHELL}} rm -r -fo .pytest_cache/'
      - '{{.SHELL}} rm -r -fo .mypy_cache/'
      - '{{.SHELL}} rm -r -fo tse_analytics.egg-info/'
      - '{{.SHELL}} find {{.SOURCE_DIR}} -name "*_ui.py" -exec rm -f {} +'
      - '{{.SHELL}} find {{.SOURCE_DIR}} -name "*_rc.py" -exec rm -f {} +'
    ignore_error: true

  coverage:
    desc: check code coverage
    cmds:
      - pytest --cov=$(SOURCE_DIR) tests/

  create-setup:
    cmds:
      - uv sync
      - pyinstaller --clean setup/tse-analytics.spec

  mypy:
    cmds:
      - mypy tse_analytics

  pylint:
    cmds:
      - pylint -j 8 tse_analytics
    ignore_error: true

  ruff-check:
    cmds:
      - ruff check .
    ignore_error: true

  ruff-fix:
    cmds:
      - ruff check . --fix
    ignore_error: true

  ruff-format:
    cmds:
      - ruff format .
    ignore_error: true

  test:
    cmds:
      - pytest

  qss:
    cmds:
      - qtsass ./tse_analytics/styles/scss -o ./tse_analytics/styles/qss

  update:
    cmds:
      - uv self update
      - uv lock --upgrade
      - uv sync
