version: "3"

vars:
  APP_NAME: tse-analytics
  SOURCE_DIR: tse_analytics

  # Workaround
  SHELL: '{{if eq .OS "Windows_NT"}}powershell{{end}}'

tasks:
  build-resources:
    cmds:
      - pyside6-rcc resources/resources.qrc -o tse_analytics/resources_rc.py

  build-ui:
    deps:
      - build-ui:views
      - build-ui:toolbox
      - build-ui:phenomaster
      - build-ui:intellicage
      - build-ui:intellimaze

  build-ui:views:
    cmds:
      - pyside6-uic tse_analytics/views/main_window.ui -o tse_analytics/views/main_window_ui.py
      - pyside6-uic tse_analytics/views/misc/raw_data_widget/raw_data_widget.ui -o tse_analytics/views/misc/raw_data_widget/raw_data_widget_ui.py
      - pyside6-uic tse_analytics/views/general/factors/factors_dialog.ui -o tse_analytics/views/general/factors/factors_dialog_ui.py
      - pyside6-uic tse_analytics/views/general/variables/add_variable_dialog.ui -o tse_analytics/views/general/variables/add_variable_dialog_ui.py
      - pyside6-uic tse_analytics/views/general/datasets/datasets_merge_dialog.ui -o tse_analytics/views/general/datasets/datasets_merge_dialog_ui.py
      - pyside6-uic tse_analytics/views/general/datasets/adjust_dataset_dialog.ui -o tse_analytics/views/general/datasets/adjust_dataset_dialog_ui.py
      - pyside6-uic tse_analytics/views/general/settings/binning_settings_widget.ui -o tse_analytics/views/general/settings/binning_settings_widget_ui.py
      - pyside6-uic tse_analytics/views/general/about/about_dialog.ui -o tse_analytics/views/general/about/about_dialog_ui.py
      - pyside6-uic tse_analytics/views/general/settings/settings_dialog.ui -o tse_analytics/views/general/settings/settings_dialog_ui.py

  build-ui:toolbox:
    cmds:
      - pyside6-uic tse_analytics/toolbox/n_way_anova/n_way_anova_settings_widget.ui -o tse_analytics/toolbox/n_way_anova/n_way_anova_settings_widget_ui.py
      - pyside6-uic tse_analytics/toolbox/rm_anova/rm_anova_settings_widget.ui -o tse_analytics/toolbox/rm_anova/rm_anova_settings_widget_ui.py
      - pyside6-uic tse_analytics/toolbox/mixed_anova/mixed_anova_settings_widget.ui -o tse_analytics/toolbox/mixed_anova/mixed_anova_settings_widget_ui.py
      - pyside6-uic tse_analytics/toolbox/ancova/ancova_settings_widget.ui -o tse_analytics/toolbox/ancova/ancova_settings_widget_ui.py
      - pyside6-uic tse_analytics/toolbox/reports/reports_widget.ui -o tse_analytics/toolbox/reports/reports_widget_ui.py

  build-ui:phenomaster:
    cmds:
      - pyside6-uic tse_analytics/modules/phenomaster/views/import_csv_dialog.ui -o tse_analytics/modules/phenomaster/views/import_csv_dialog_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/views/import_tse_dialog.ui -o tse_analytics/modules/phenomaster/views/import_tse_dialog_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/drinkfeed/views/drinkfeed_dialog.ui -o tse_analytics/modules/phenomaster/submodules/drinkfeed/views/drinkfeed_dialog_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/drinkfeed/views/settings/settings_widget.ui -o tse_analytics/modules/phenomaster/submodules/drinkfeed/views/settings/settings_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/calo/views/calo_dialog.ui -o tse_analytics/modules/phenomaster/submodules/calo/views/calo_dialog_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/calo/views/plot/plot_widget.ui -o tse_analytics/modules/phenomaster/submodules/calo/views/plot/plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/calo/views/settings/settings_widget.ui -o tse_analytics/modules/phenomaster/submodules/calo/views/settings/settings_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/calo/views/settings/gas_settings/gas_settings_widget.ui -o tse_analytics/modules/phenomaster/submodules/calo/views/settings/gas_settings/gas_settings_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/calo/views/test_fit/test_fit_widget.ui -o tse_analytics/modules/phenomaster/submodules/calo/views/test_fit/test_fit_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/calo/views/rer/rer_widget.ui -o tse_analytics/modules/phenomaster/submodules/calo/views/rer/rer_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_dialog.ui -o tse_analytics/modules/phenomaster/submodules/actimot/views/actimot_dialog_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/actimot/views/plot/plot_widget.ui -o tse_analytics/modules/phenomaster/submodules/actimot/views/plot/plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/actimot/views/settings/settings_widget.ui -o tse_analytics/modules/phenomaster/submodules/actimot/views/settings/settings_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/actimot/views/stream/stream_widget.ui -o tse_analytics/modules/phenomaster/submodules/actimot/views/stream/stream_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/actimot/views/heatmap/heatmap_widget.ui -o tse_analytics/modules/phenomaster/submodules/actimot/views/heatmap/heatmap_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/actimot/views/trajectory/trajectory_widget.ui -o tse_analytics/modules/phenomaster/submodules/actimot/views/trajectory/trajectory_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/actimot/views/frames/frames_widget.ui -o tse_analytics/modules/phenomaster/submodules/actimot/views/frames/frames_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/grouphousing/views/grouphousing_dialog.ui -o tse_analytics/modules/phenomaster/submodules/grouphousing/views/grouphousing_dialog_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/grouphousing/views/heatmap/heatmap_widget.ui -o tse_analytics/modules/phenomaster/submodules/grouphousing/views/heatmap/heatmap_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/grouphousing/views/raw_data/raw_data_widget.ui -o tse_analytics/modules/phenomaster/submodules/grouphousing/views/raw_data/raw_data_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/submodules/grouphousing/views/preprocessed_data/preprocessed_data_widget.ui -o tse_analytics/modules/phenomaster/submodules/grouphousing/views/preprocessed_data/preprocessed_data_widget_ui.py

  build-ui:intellicage:
    cmds:
      - pyside6-uic tse_analytics/modules/intellicage/toolbox/place_preference/place_preference_settings_widget.ui -o tse_analytics/modules/intellicage/toolbox/place_preference/place_preference_settings_widget_ui.py

  build-ui:intellimaze:
    cmds:
      - pyside6-uic tse_analytics/modules/intellimaze/views/export_merged_csv/export_merged_csv_dialog.ui -o tse_analytics/modules/intellimaze/views/export_merged_csv/export_merged_csv_dialog_ui.py

  clean:
    desc: remove all build, test, coverage and Python artifacts
    cmds:
      - '{{.SHELL}} rm -r -fo __pycache__/'
      - '{{.SHELL}} rm -r -fo build/'
      - '{{.SHELL}} rm -r -fo dist/'
      - '{{.SHELL}} rm -r -fo .pytest_cache/'
      - '{{.SHELL}} rm -r -fo .mypy_cache/'
      - '{{.SHELL}} rm -r -fo tse_analytics.egg-info/'
      - '{{.SHELL}} find {{.SOURCE_DIR}} -name "*_ui.py" -exec rm -f {} +'
      - '{{.SHELL}} find {{.SOURCE_DIR}} -name "*_rc.py" -exec rm -f {} +'
    ignore_error: true

  coverage:
    desc: check code coverage
    cmds:
      - pytest --cov=$(SOURCE_DIR) tests/

  deploy:
    cmds:
      - uv sync
      - pyinstaller --clean setup/tse-analytics.spec

  deploy-pyside:
    cmds:
      - uv sync
      - pyside6-deploy -c pysidedeploy.spec

  mypy:
    cmds:
      - mypy tse_analytics

  ty:
    cmds:
      - ty check
    ignore_error: true

  pylint:
    cmds:
      - pylint -j 8 tse_analytics
    ignore_error: true

  ruff-check:
    cmds:
      - ruff check .
    ignore_error: true

  ruff-fix:
    cmds:
      - ruff check . --fix
    ignore_error: true

  ruff-format:
    cmds:
      - ruff format .
    ignore_error: true

  test:
    cmds:
      - pytest

  qss:
    cmds:
      - qtsass ./tse_analytics/styles/scss -o ./tse_analytics/styles/qss

  update:
    cmds:
      - uv self update
      - uv lock --upgrade
      - uv sync
