version: "3"

vars:
  APP_NAME: tse-analytics
  SOURCE_DIR: tse_analytics

  # Workaround
  SHELL: '{{if eq .OS "Windows_NT"}}powershell{{end}}'

tasks:
  build-resources:
    cmds:
      - pyside6-rcc resources/resources.qrc -o tse_analytics/resources_rc.py

  build-ui:
    cmds:
      - pyside6-uic tse_analytics/views/main_window.ui -o tse_analytics/views/main_window_ui.py
      - pyside6-uic tse_analytics/views/import_csv_dialog.ui -o tse_analytics/views/import_csv_dialog_ui.py
      - pyside6-uic tse_analytics/views/import_tse_dialog.ui -o tse_analytics/views/import_tse_dialog_ui.py
      - pyside6-uic tse_analytics/views/factors_dialog.ui -o tse_analytics/views/factors_dialog_ui.py
      - pyside6-uic tse_analytics/views/datasets/datasets_widget.ui -o tse_analytics/views/datasets/datasets_widget_ui.py
      - pyside6-uic tse_analytics/views/datasets/datasets_merge_dialog.ui -o tse_analytics/views/datasets/datasets_merge_dialog_ui.py
      - pyside6-uic tse_analytics/views/datasets/adjust_dataset_dialog.ui -o tse_analytics/views/datasets/adjust_dataset_dialog_ui.py
      - pyside6-uic tse_analytics/views/selection/factors/factors_widget.ui -o tse_analytics/views/selection/factors/factors_widget_ui.py
      - pyside6-uic tse_analytics/views/selection/animals/animals_widget.ui -o tse_analytics/views/selection/animals/animals_widget_ui.py
      - pyside6-uic tse_analytics/views/selection/variables/variables_widget.ui -o tse_analytics/views/selection/variables/variables_widget_ui.py
      - pyside6-uic tse_analytics/views/data/data_table_widget.ui -o tse_analytics/views/data/data_table_widget_ui.py
      - pyside6-uic tse_analytics/views/data/data_plot_widget.ui -o tse_analytics/views/data/data_plot_widget_ui.py
      - pyside6-uic tse_analytics/views/settings/time_intervals_settings_widget.ui -o tse_analytics/views/settings/time_intervals_settings_widget_ui.py
      - pyside6-uic tse_analytics/views/settings/time_cycles_settings_widget.ui -o tse_analytics/views/settings/time_cycles_settings_widget_ui.py
      - pyside6-uic tse_analytics/views/settings/time_phases_settings_widget.ui -o tse_analytics/views/settings/time_phases_settings_widget_ui.py
      - pyside6-uic tse_analytics/views/settings/binning_settings_widget.ui -o tse_analytics/views/settings/binning_settings_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/histogram/histogram_widget.ui -o tse_analytics/views/analysis/histogram/histogram_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/distribution/distribution_widget.ui -o tse_analytics/views/analysis/distribution/distribution_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/normality/normality_widget.ui -o tse_analytics/views/analysis/normality/normality_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/correlation/correlation_widget.ui -o tse_analytics/views/analysis/correlation/correlation_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/regression/regression_widget.ui -o tse_analytics/views/analysis/regression/regression_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/matrixplot/matrixplot_widget.ui -o tse_analytics/views/analysis/matrixplot/matrixplot_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/pca/pca_widget.ui -o tse_analytics/views/analysis/pca/pca_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/tsne/tsne_widget.ui -o tse_analytics/views/analysis/tsne/tsne_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/one_way_anova/one_way_anova_widget.ui -o tse_analytics/views/analysis/one_way_anova/one_way_anova_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/n_way_anova/n_way_anova_widget.ui -o tse_analytics/views/analysis/n_way_anova/n_way_anova_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/rm_anova/rm_anova_widget.ui -o tse_analytics/views/analysis/rm_anova/rm_anova_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/mixed_anova/mixed_anova_widget.ui -o tse_analytics/views/analysis/mixed_anova/mixed_anova_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/ancova/ancova_widget.ui -o tse_analytics/views/analysis/ancova/ancova_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/timeseries_decomposition/timeseries_decomposition_widget.ui -o tse_analytics/views/analysis/timeseries_decomposition/timeseries_decomposition_widget_ui.py
      - pyside6-uic tse_analytics/views/analysis/timeseries_autocorrelation/timeseries_autocorrelation_widget.ui -o tse_analytics/views/analysis/timeseries_autocorrelation/timeseries_autocorrelation_widget_ui.py
      - pyside6-uic tse_analytics/views/about_dialog.ui -o tse_analytics/views/about_dialog_ui.py
      - pyside6-uic tse_analytics/views/reports/reports_widget.ui -o tse_analytics/views/reports/reports_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/meal_details/views/meal_details_dialog.ui -o tse_analytics/modules/phenomaster/meal_details/views/meal_details_dialog_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/meal_details/views/meal_details_plot_widget.ui -o tse_analytics/modules/phenomaster/meal_details/views/meal_details_plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/meal_details/views/meal_details_settings_widget.ui -o tse_analytics/modules/phenomaster/meal_details/views/meal_details_settings_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/meal_details/views/meal_episodes_plot_widget.ui -o tse_analytics/modules/phenomaster/meal_details/views/meal_episodes_plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/calo_details/views/calo_details_dialog.ui -o tse_analytics/modules/phenomaster/calo_details/views/calo_details_dialog_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/calo_details/views/calo_details_plot_widget.ui -o tse_analytics/modules/phenomaster/calo_details/views/calo_details_plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/calo_details/views/calo_details_settings_widget.ui -o tse_analytics/modules/phenomaster/calo_details/views/calo_details_settings_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/calo_details/views/calo_details_gas_settings_widget.ui -o tse_analytics/modules/phenomaster/calo_details/views/calo_details_gas_settings_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/calo_details/views/calo_details_test_fit_widget.ui -o tse_analytics/modules/phenomaster/calo_details/views/calo_details_test_fit_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/calo_details/views/calo_details_rer_widget.ui -o tse_analytics/modules/phenomaster/calo_details/views/calo_details_rer_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/actimot/views/actimot_dialog.ui -o tse_analytics/modules/phenomaster/actimot/views/actimot_dialog_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/actimot/views/actimot_plot_widget.ui -o tse_analytics/modules/phenomaster/actimot/views/actimot_plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/actimot/views/actimot_settings_widget.ui -o tse_analytics/modules/phenomaster/actimot/views/actimot_settings_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/actimot/views/actimot_stream_plot_widget.ui -o tse_analytics/modules/phenomaster/actimot/views/actimot_stream_plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/actimot/views/actimot_heatmap_plot_widget.ui -o tse_analytics/modules/phenomaster/actimot/views/actimot_heatmap_plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/actimot/views/actimot_trajectory_plot_widget.ui -o tse_analytics/modules/phenomaster/actimot/views/actimot_trajectory_plot_widget_ui.py
      - pyside6-uic tse_analytics/modules/phenomaster/actimot/views/actimot_frames_widget.ui -o tse_analytics/modules/phenomaster/actimot/views/actimot_frames_widget_ui.py
      - pyside6-uic tse_analytics/modules/intellimaze/animal_gate/views/animal_gate_dialog.ui -o tse_analytics/modules/intellimaze/animal_gate/views/animal_gate_dialog_ui.py
      - pyside6-uic tse_analytics/modules/intellimaze/running_wheel/views/running_wheel_dialog.ui -o tse_analytics/modules/intellimaze/running_wheel/views/running_wheel_dialog_ui.py
      - pyside6-uic tse_analytics/modules/intellimaze/consumption_scale/views/consumption_scale_dialog.ui -o tse_analytics/modules/intellimaze/consumption_scale/views/consumption_scale_dialog_ui.py

  clean:
    desc: remove all build, test, coverage and Python artifacts
    cmds:
      - '{{.SHELL}} rm -r -fo __pycache__/'
      - '{{.SHELL}} rm -r -fo build/'
      - '{{.SHELL}} rm -r -fo dist/'
      - '{{.SHELL}} rm -r -fo .pytest_cache/'
      - '{{.SHELL}} rm -r -fo .mypy_cache/'
      - '{{.SHELL}} rm -r -fo tse_analytics.egg-info/'
      - '{{.SHELL}} find {{.SOURCE_DIR}} -name "*_ui.py" -exec rm -f {} +'
      - '{{.SHELL}} find {{.SOURCE_DIR}} -name "*_rc.py" -exec rm -f {} +'
    ignore_error: true

  coverage:
    desc: check code coverage
    cmds:
      - pytest --cov=$(SOURCE_DIR) tests/

  create-setup:
    cmds:
      - uv sync
      - pyinstaller --clean setup/tse-analytics.spec

  mypy:
    cmds:
      - mypy tse_analytics

  pylint:
    cmds:
      - pylint -j 8 tse_analytics
    ignore_error: true

  ruff-check:
    cmds:
      - ruff check .
    ignore_error: true

  ruff-fix:
    cmds:
      - ruff check . --fix
    ignore_error: true

  ruff-format:
    cmds:
      - ruff format .
    ignore_error: true

  test:
    cmds:
      - pytest

  qss:
    cmds:
      - qtsass ./tse_analytics/styles/scss -o ./tse_analytics/styles/qss
