"""Export a Dataset's analysis log as a runnable Jupyter notebook.

The output is a `.ipynb` that, when run end-to-end, re-applies every recorded
mutation against a fresh load of the raw source data. The first code cell is
a TODO placeholder for the source path, since the original `.tse` workspace
holds only the *processed* state — the user must point the notebook at the
underlying raw data files (PhenoMaster directory, IntelliCage SQLite, etc.).
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import nbformat
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

from tse_analytics.core.data.dataset import Dataset
from tse_analytics.core.export.notebook_codegen import codegen_for_action


def _header_markdown(dataset: Dataset) -> str:
    source_path = dataset.metadata.get("source_path", "") if isinstance(dataset.metadata, dict) else ""
    lines = [
        f"# Reproducibility notebook — `{dataset.name}`",
        "",
        "Generated by **TSE Analytics**. Re-running this notebook reproduces the",
        f"recorded analysis log for dataset *{dataset.name}* against a fresh load of the raw data.",
        "",
        f"- **Dataset type**: `{dataset.dataset_type}`",
        f"- **Source path**: `{source_path or '(not recorded)'}`",
        f"- **Exported**: {datetime.now().isoformat(timespec='seconds')}",
        f"- **Recorded actions**: {len(dataset.analysis_log)}",
    ]
    return "\n".join(lines)


def _imports_cell() -> str:
    return (
        "from datetime import datetime\n"
        "from pathlib import Path\n"
        "\n"
        "from pydantic import TypeAdapter\n"
        "\n"
        "from tse_analytics.core.data.binning import TimeIntervalsBinningSettings\n"
        "from tse_analytics.core.data.datatable import Datatable\n"
        "from tse_analytics.core.data.shared import Animal, Factor\n"
        "from tse_analytics.views.datasets.edit_datatable.processor import process_table"
    )


def _load_cell(dataset: Dataset) -> str:
    source_path = dataset.metadata.get("source_path", "") if isinstance(dataset.metadata, dict) else ""
    path_repr = repr(source_path) if source_path else 'r"<RAW DATA PATH>"'

    if dataset.dataset_type == "PhenoMaster":
        return (
            "# TODO: confirm the raw-data path below points to the original PhenoMaster source.\n"
            "from tse_analytics.modules.phenomaster.io.tse_dataset_loader import load_tse_dataset\n"
            "from tse_analytics.modules.phenomaster.io.tse_import_settings import TseImportSettings\n"
            "\n"
            f"source_path = Path({path_repr})\n"
            "dataset = load_tse_dataset(source_path, TseImportSettings())\n"
            "assert dataset is not None, 'Failed to load source dataset'"
        )
    if dataset.dataset_type == "IntelliCage":
        return (
            "# TODO: confirm the raw-data path below points to the original IntelliCage archive.\n"
            "from tse_analytics.modules.intellicage.io.dataset_loader import load_dataset\n"
            "\n"
            f"source_path = Path({path_repr})\n"
            "dataset = load_dataset(source_path)\n"
            "assert dataset is not None, 'Failed to load source dataset'"
        )
    if dataset.dataset_type == "IntelliMaze":
        return (
            "# TODO: confirm the raw-data path below points to the original IntelliMaze archive.\n"
            "from tse_analytics.modules.intellimaze.io.dataset_loader import load_dataset\n"
            "\n"
            f"source_path = Path({path_repr})\n"
            "dataset = load_dataset(source_path)\n"
            "assert dataset is not None, 'Failed to load source dataset'"
        )
    return (
        f"# TODO: load the raw data for dataset_type={dataset.dataset_type!r}\n"
        f"source_path = Path({path_repr})\n"
        "dataset = ...  # invoke the appropriate loader"
    )


def _final_cell() -> str:
    return (
        "# Resulting state after replay\n"
        "print('Datatables:', list(dataset.datatables.keys()))\n"
        "print('Factors:', list(dataset.factors.keys()))\n"
        "print('Animals:', len(dataset.animals))"
    )


def export_dataset_as_notebook(dataset: Dataset, output_path: Path) -> None:
    """Write a `.ipynb` that replays ``dataset.analysis_log`` against the raw source data."""
    notebook = new_notebook()
    notebook.cells.append(new_markdown_cell(_header_markdown(dataset)))
    notebook.cells.append(new_code_cell(_imports_cell()))
    notebook.cells.append(new_code_cell(_load_cell(dataset)))

    for action in dataset.analysis_log:
        notebook.cells.append(new_code_cell(codegen_for_action(action)))

    notebook.cells.append(new_code_cell(_final_cell()))

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as fh:
        nbformat.write(notebook, fh)
